name: PR Tests and Build

on:
  pull_request:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (if using Node.js)
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: CI=true npm test -- --watchAll

      - name: Build project
        run: npm run build
      
        
      - name: Install Trivy
        run: |
          curl -sSfL https://github.com/aquasecurity/trivy/releases/download/v0.39.0/trivy_0.39.0_Linux-x86_64.deb -o trivy.deb
          sudo dpkg -i trivy.deb
          trivy --version

      - name: Scan Docker image for vulnerabilities
        run: |
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-node-app:latest
          trivy image ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-node-app:latest